meta_product_name: "Wedpacker"
meta_title: "Wedpacker - Organisez votre mariage en quelques clics !"
meta_description: "Quel heureux événement qu’un mariage en perspective ! Et pourtant, les mois précédants le jour J peuvent parfois s’avérer être un vrai parcours du combattant, à la fois compliqué et stressant.
Une organisation sans prise de tête, c'est possible ! Wedpacker facilite vos préparatifs avec un concept simple et innovant."
meta_image: "http://resizeimage.net/viewimg/8T4z47Eg3XaDWlFl/1IZBe/wedding-banner.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_lewagonparis"   # required for Twitter Cards


